export const LOADING_LOGIN = 'LOADING_LOGIN'
export const LOGIN_SUCCESSFUL = 'LOGIN_SUCCESSFUL'
export const LOGIN_UNSUCCESSFUL = 'LOGIN_UNSUCCESSFUL'
export const LOGOUT_SUCCESSFUL = 'LOGOUT_SUCCESSFUL'
